<?php

final class WP_Ulike_Pro_Avatar_Controller extends wp_ulike_ajax_listener_base {

	public function __construct(){
		parent::__construct();
		$this->setFormData();
		$this->process();
	}

	/**
	 * Set Form Data
	 *
	 * @return void
	 */
	private function setFormData(){
		$this->data['security'] = isset( $_POST['security'] ) ? sanitize_text_field( wp_unslash( $_POST['security'] ) ) : NULL;
		$this->data['name']     = isset( $_POST['name'] ) ? sanitize_file_name( wp_unslash( $_POST['name'] ) ) : NULL;
		$this->data['method']   = isset( $_POST['method'] ) ? sanitize_text_field( wp_unslash( $_POST['method'] ) ) : NULL;

		// Delete Args
		$this->data['file'] = isset( $_POST['file'] ) ? sanitize_file_name( wp_unslash( $_POST['file'] ) ) : NULL;
		$this->data['remove_meta'] = isset( $_POST['removeMeta'] ) ? (bool) wp_unslash( $_POST['removeMeta'] ) : false;

		$configurations = WP_Ulike_Pro_Options::getAvatarConfigs();

		// Configs
		$this->data['configs']  = [
			'limit'       => 1,
			'fileMaxSize' => $configurations['maxSize'],
			'extensions'  => ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'],
			'title'       => 'auto',
			'uploadDir'   => WP_ULIKE_CUSTOM_DIR . '/avatars/',
			'replace'     => false,
			'editor'      => [
				'maxWidth'  => $configurations['maxWidth'],
				'maxHeight' => $configurations['maxWidth'],
				'crop'      => false,
				'quality'   => $configurations['quality']
			]
		];
	}

	/**
	 * Process request
	 *
	 * @return void
	 */
	public function process(){
		// Output args
        $data = array(
            "hasWarnings" => false,
            "isSuccess"   => false,
            "warnings"    => array(),
            "files"       => array()
        );

		try {
			$this->beforeAction();

			$this->validates();

			if ( $this->data['method'] === 'upload' ) {

				// Validate file upload exists
				if ( ! isset( $_FILES['files'] ) || empty( $_FILES['files']['tmp_name'] ) ) {
					throw new \Exception( esc_html__( 'No file uploaded.', WP_ULIKE_PRO_DOMAIN ) );
				}

				// Prepare uploader configuration
				$configurations = WP_Ulike_Pro_Options::getAvatarConfigs();

				// Generate filename: {user_id}-{hash}.{ext}
				// Format used by popular services (Facebook, Twitter, Instagram style)
				// Secure, organized, unique per user, easy to manage
				$user_id = ! empty( $this->user ) ? (int) $this->user : 0;
				$filename_pattern = null; // Will be generated by uploader with user context

				// Delete previous avatar if exists (for better performance)
				// Get existing avatar data from user meta
				$existing_avatar_data = get_user_meta( $user_id, 'ulp_avatar_data', true );
				
				if ( ! empty( $existing_avatar_data['name'] ) ) {
					// Security: Sanitize and validate filename
					$existing_name = sanitize_file_name( basename( $existing_avatar_data['name'] ) );
					$existing_name = str_replace( array( '/', '\\', '..', "\0" ), '', $existing_name ); // Additional sanitization

					// Security: Verify user owns this file (check user_id prefix)
					if ( preg_match( '/^' . preg_quote( $user_id, '/' ) . '-/', $existing_name ) ) {
						$existing_path = $this->data['configs']['uploadDir'] . $existing_name;

						// Security: Path traversal check
						$real_upload_dir = realpath( $this->data['configs']['uploadDir'] );
						$real_existing_file = realpath( $existing_path );

						if ( $real_upload_dir && $real_existing_file && strpos( $real_existing_file, $real_upload_dir ) === 0 && is_file( $existing_path ) ) {
							// Delete previous avatar file to free up space
							@unlink( $existing_path );
						}
					}
				}

				$uploader_config = array(
					'max_size'      => $configurations['maxSize'],
					'allowed_types' => $this->data['configs']['extensions'],
					'upload_dir'    => $this->data['configs']['uploadDir'],
					'replace'       => ! empty( $filename_pattern ) ? true : false,
					'filename'      => $filename_pattern, // Will be generated as {user_id}-{hash} if null
					'user_id'       => $user_id, // Pass user ID for filename generation
					'quality'       => $configurations['quality'],
					'max_width'     => $configurations['maxWidth'],
					'max_height'    => $configurations['maxWidth'],
				);

				// Upload file using WordPress standard file uploader
				$uploader = new WP_Ulike_Pro_WordPress_File_Uploader( $_FILES['files'], $uploader_config );
				$upload_result = $uploader->upload();

				if ( is_wp_error( $upload_result ) ) {
					$data['isSuccess'] = false;
					$data['hasWarnings'] = true;
					$data['warnings'][] = $upload_result->get_error_message();
				} else {
					// Build file data array (compatible with old structure)
					$item = array(
						'name'      => $upload_result['name'],
						'title'     => $upload_result['title'],
						'size'      => $upload_result['size'],
						'size2'     => $upload_result['size2'],
						'type'      => $upload_result['type'],
						'extension' => $upload_result['extension'],
						'file'      => $upload_result['url'],
						'uploaded'  => true
					);

					// Update avatar meta
					update_user_meta( $this->user, 'ulp_avatar_data', $item );

					// Update avatar url
					update_user_meta( $this->user, 'ulp_avatar', array(
						'url' => $upload_result['url']
					) );

					// Return data in expected format
					$data['isSuccess'] = true;
					$data['files'] = array(
						array(
							'title' => $item['title'],
							'name'  => $item['name'],
							'size'  => $item['size'],
							'size2' => $item['size2'],
							'url'   => $item['file']
						)
					);
				}
			} elseif( $this->data['method'] === 'delete' && ! empty( $this->data['file'] ) ) {
				// Security: Verify user can only delete their own avatar
				$user_id = ! empty( $this->user ) ? (int) $this->user : 0;
				if ( empty( $user_id ) ) {
					throw new \Exception( esc_html__( 'Invalid item.', WP_ULIKE_PRO_DOMAIN ) );
				}

				// Sanitize filename to prevent directory traversal
				$filename = sanitize_file_name( basename( $this->data['file'] ) );
				$filename = str_replace( array( '/', '\\', '..', "\0" ), '', $filename ); // Additional sanitization

				// Security: Verify filename matches user's avatar (user_id prefix)
				// This prevents users from deleting other users' avatars
				if ( ! preg_match( '/^' . preg_quote( $user_id, '/' ) . '-/', $filename ) ) {
					throw new \Exception( esc_html__( 'You can only delete your own avatar.', WP_ULIKE_PRO_DOMAIN ) );
				}

				$file = $this->data['configs']['uploadDir'] . $filename;

				// Additional security: ensure file is within upload directory (path traversal check)
				$real_upload_dir = realpath( $this->data['configs']['uploadDir'] );
				$real_file = realpath( $file );

				if ( ! $real_upload_dir ) {
					throw new \Exception( esc_html__( 'Upload directory does not exist.', WP_ULIKE_PRO_DOMAIN ) );
				}

				if ( ! $real_file ) {
					throw new \Exception( esc_html__( 'Item does not exist.', WP_ULIKE_PRO_DOMAIN ) );
				}

				// Critical security check: ensure file is actually within upload directory
				if ( strpos( $real_file, $real_upload_dir ) !== 0 ) {
					throw new \Exception( esc_html__( 'Security check failed. Invalid file path.', WP_ULIKE_PRO_DOMAIN ) );
				}

				// Verify it's actually a file (not directory)
				if ( ! is_file( $real_file ) ) {
					throw new \Exception( esc_html__( 'Invalid item.', WP_ULIKE_PRO_DOMAIN ) );
				}

				// Additional security: Verify file belongs to this user by checking user meta
				$user_avatar_data = get_user_meta( $user_id, 'ulp_avatar_data', true );
				if ( ! empty( $user_avatar_data['name'] ) && $user_avatar_data['name'] !== $filename ) {
					// File in meta doesn't match - extra verification
					// But allow if filename has user_id prefix (already checked above)
				}

				// All security checks passed, delete file
				if ( @unlink( $real_file ) ) {
					// Delete meta
					if( $this->data['remove_meta'] ){
						delete_user_meta( $user_id, 'ulp_avatar_data' );
						delete_user_meta( $user_id, 'ulp_avatar' );
					}
					// Change message
					$data['isSuccess'] = true;
				} else {
					throw new \Exception( esc_html__( 'Failed to delete file.', WP_ULIKE_PRO_DOMAIN ) );
				}
			}

            $this->afterAction();

		} catch ( \Exception $e ){
			$data['hasWarnings'] = true;
			$data['warnings'] = array(
				$e->getMessage()
			);
		}

		wp_send_json( $data );
	}

	/**
	* Before Action
	* Provides hook for performing actions before a process
	*/
	private function beforeAction(){
		do_action_ref_array('wp_ulike_pro_before_avatar_process', array( &$this ) );
	}

	/**
	* After Action
	* Provides hook for performing actions after a process
	*/
	private function afterAction(){
		do_action_ref_array( 'wp_ulike_pro_after_avatar_process', array( &$this ) );
    }

	/**
	* Validate the Favorite
	*/
	private function validates(){
		// Return false when nonce invalid
		if( ! wp_verify_nonce( $this->data['security'], WP_ULIKE_PRO_DOMAIN ) || ! $this->user ){
            throw new \Exception( WP_Ulike_Pro_Options::getNoticeMessage( 'permission_denied', esc_html__( 'Something went wrong. Please try again or contact the admin.', WP_ULIKE_PRO_DOMAIN ) ) );
        }
		// Check methods
		if( empty( $this->data['method'] ) || ! in_array( $this->data['method'], array( 'upload','delete' ) ) ){
			throw new \Exception( esc_html__( 'Not found!', WP_ULIKE_PRO_DOMAIN ) );
		}
	}

}